spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hzautrade?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: 20020419

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 1000MB


  mail:
    host: smtp.163.com
    port: 25
    username: lxy13628688240@163.com
    password: JEGOCBPVTQNTKSQU
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #显示邮件发送信息
        debug: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ct.model

server:
  port: 1024


  #支付宝前端响应地址
  ipAddr: http://localhost:8080/
